"""Added account table

Revision ID: 0aa608456abb
Revises: 30c7128f4502
Create Date: 2023-03-06 17:25:36.813325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa608456abb'
down_revision = '30c7128f4502'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
